services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - /share/Container/jekyll/zhengyuan-public.github.io:/site
      - /share/Container/jekyll/bundle:/usr/local/bundle
    ports:
      - 4000:4000
    network_mode: bridge
    restart: unless-stopped
    stdin_open: true      # Enable stdin
    tty: true             # Allocate a pseudo-TTY